### ISSUE TITLE
Add GUI to the main

### ISSUE THREAD

**Issue by Akatsuki06** [Akatsuki06/AutonomousCarAI#1]
Add a simple GUI using pyqt5 in python for the main.py it should contain the train and test buttons. Thats it!

**Comment by aeroaks** [comment]
I am on it!

**Comment by Akatsuki06** [comment]
Okay go for it

**Comment by Shubhamsharma09** [comment]
Can't we use Tkinter GUI?

**Comment by aeroaks** [comment]
@Shubhamsharma09 We can... and it would reduce an extra dependency!

**Comment by Akatsuki06** [comment]
Yes, sure  @Shubhamsharma09  and @aeroaks

**Comment by Shubhamsharma09** [comment]
okk

**Comment by aeroaks** [comment]
I have 2 screens, and the Game was running on one screen. I tested pyautogui using screenshot option and it was reading the screen that I had the game open in. 
Thanks for accepting. Would be interested to make it working with errors and is it running on my PC. :)

**Comment by Akatsuki06** [comment]
Well, its fine! There was some error that's fixed now.
If you wanna contribute further you are welcome @aeroaks
