### ISSUE TITLE
Rename contributors.md to CONTRIBUTING.md file. Fix the markdown and mistakes in CONTRIBUTING.md file

### ISSUE THREAD

**Issue by Akatsuki06** [Akatsuki06/AutonomousCarAI#11]
put the member contributors  in the file, the one contributing can be easily found in contributors tab.

**Comment by devAmoghS** [comment]
@Akatsuki06 Will be happy to help you. BTW, I am also a huge Naruto fan !

**Comment by Akatsuki06** [comment]
@devAmoghS sure ;)

**Comment by music-mind** [comment]
I'll like to help as well!

**Comment by Akatsuki06** [comment]
Sure

**Comment by SandySingh** [comment]
I'll be happy to help
