### ISSUE TITLE
Update the README and correct grammatical errors and redundant punctutations.

### ISSUE THREAD

**Issue by Akatsuki06** [Akatsuki06/AutonomousCarAI#2]
easy just update it ;)

**Comment by skolerst** [comment]
I got this

**Comment by Akatsuki06** [comment]
@skolerst go for it buddy

**Comment by Helithumper** [comment]
I'll run a second check on the grammar, just to be safe :) #7

**Comment by yacheegupta** [comment]
Hi !  I am interested in updating the README and will check all the grammatical errors and redundant punctutations wherever it occurs.
